name: "Run static analysis"
description: "A GitHub Action to perform static analysis using SonarQube."
inputs:
  project_dir:
    description: "Root directory of the project."
    required: true
  SONAR_HOST_URL:
    description: "The URL of the SonarQube server."
    required: true
  SONAR_TOKEN:
    description: "Authentication token for SonarQube."
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug Inputs
      run: |
        echo "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}"
        echo "SONAR_TOKEN=[REDACTED]"
      shell: bash

    - name: "SonarQube/Cloud Scan"
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.projectKey=StudentReportLLM
          -Dsonar.organization=studentreportllm
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
