global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:9090' ]
    honor_labels: true # prevent prometheus from overriding job and instance labels and use those that were sent by the otel collector