name: "Run unit tests"
inputs:
  project_dir:
    description: "Root directory of the project. Should contain `src` and `tests` directories."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      run: |
        cd ${{ inputs.project_dir }}
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
      shell: bash

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=${{ github.workspace }}/${{ inputs.project_dir }}/src" >> $GITHUB_ENV
      shell: bash

    - name: Run Python tests
      run: |
        cd ${{ inputs.project_dir }}
        python -m unittest discover tests
      shell: bash