name: "Run unit tests"
inputs:
  project_dir:
    description: "Root directory of the project. Should contain `src` and `tests` directories."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      run: |
        cd ${{ inputs.project_dir }}
        pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=${{ inputs.project_dir }}/src" >> $GITHUB_ENV
      shell: bash

    - name: Debug PYTHONPATH
      run: |
        echo "PYTHONPATH is set to: $PYTHONPATH"
        ls -R $PYTHONPATH
      shell: bash

    - name: Run Python tests
      run: |
        cd ${{ inputs.project_dir }}
        export PYTHONPATH=${{ inputs.project_dir }}/src
        python -m unittest discover tests
      shell: bash