name: "Run unit tests"
inputs:
  project_dir:
    description: "Root directory of the project. Should contain `src` and `test` directories."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      run: |
        cd ${{ inputs.project_dir }}
        pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Run Python tests
      run: |
        cd ${{ inputs.project_dir }}
        python -m unittest discover tests
      shell: bash