name: "CI/CD pipeline for conversion service"
on:
  push:
    paths:
      - 'services/conversion/**'
  pull_request:
    paths:
      - 'services/conversion/**'
  workflow_dispatch:

env:
  project_dir: 'services/conversion'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check docker build
        uses: ./.github/actions/docker-check-build
        with:
          context: ${{ env.project_dir }}

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        uses: ./.github/actions/run-python-tests
        with:
          project_dir: ${{ env.project_dir }}
      - name: Run static code analysis
        uses: ./.github/actions/static-analysis
        with:
          project_dir: ${{ env.project_dir }}

  integration-tests:
    runs-on: ubuntu-latest
    needs: [ build, unit-tests ]
    steps:
      - uses: actions/checkout@v3
      - name: Check docker compose
        uses: ./.github/actions/check-docker-compose

  # todo: deploy