name: SonarQube Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SonarQube/Cloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=StudentReportLLM
            -Dsonar.organization=studentreportllm
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
